pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/lalithyack/bloomdailyhub-devops'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t instantprachi/bloomdailyhub .'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                sh 'docker push instantprachi/bloomdailyhub'
            }
        }
    }
}
